title: "Thurlun - Memecoin"
description: "Thurlun é uma criptomoeda inovadora baseada na Binance Smart Chain (BEP-20)."
url: "https://seusite.github.io"
baseurl: "" # Deixe vazio se for um site root
author: "Thurlun Team"
theme: "jekyll-theme-slate"  # Você pode escolher um tema Jekyll ou remover essa linha se for criar um layout manualmente
